# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generateLorAccept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aName', models.CharField(max_length=50)),
                ('aDesignation', models.CharField(max_length=50)),
                ('arequestingFirm', models.CharField(max_length=75)),
                ('askills', models.CharField(max_length=75)),
                ('projectTitle', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=50)),
                ('sDesignation', models.CharField(max_length=50)),
                ('sOrganization', models.CharField(max_length=50)),
                ('sIndustry', models.CharField(max_length=50)),
                ('smobileNumber', models.CharField(max_length=50)),
                ('semailId', models.CharField(max_length=50)),
                ('sSealImage', models.FileField(blank=True, upload_to='lor')),
                ('sSealName', models.CharField(blank=True, max_length=50, null=True)),
                ('sLinkedIn', models.CharField(blank=True, max_length=50, null=True)),
                ('rReason', models.TextField()),
                ('trait1', models.CharField(max_length=50)),
                ('trait2', models.CharField(max_length=50)),
                ('trait3', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('yoe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generateLorReject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.TextField()),
                ('rejectReason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LORRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('designation', models.TextField()),
                ('firm', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
