# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lor', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorrequest',
            name='problemId',
            field=models.ForeignKey(db_column='problemId', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
