# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lor', '0002_lorrequest_problemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorrequest',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatelorreject',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lor.LORRequest'),
        ),
        migrations.AddField(
            model_name='generateloraccept',
            name='requestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lor.LORRequest'),
        ),
    ]
