# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=70, null=True)),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('body', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('likeCounter', models.IntegerField(default=100)),
                ('viewers', django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, size=5)),
                ('published', models.BooleanField(default=False)),
                ('likeList', django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, size=None)),
                ('dislikeList', django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, size=None)),
                ('editHistory', django_mysql.models.ListTextField(models.CharField(max_length=1000), blank=True, size=None)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
