# Generated by Django 3.0.6 on 2020-10-02 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201003_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 2, 15, 13, 529742)),
        ),
    ]
