# Generated by Django 3.0.6 on 2020-10-02 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201003_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 2, 33, 8, 639711)),
        ),
    ]
