# Generated by Django 3.0.6 on 2020-12-26 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201003_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 10, 17, 41, 779963)),
        ),
    ]
