# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prototypetest', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprototypetest',
            name='solutionId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
    ]
