# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=40)),
                ('orderId', models.CharField(default='', max_length=40)),
                ('time', models.CharField(default='', max_length=40)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WalletDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=40)),
                ('cash', models.FloatField(default=0.0)),
                ('reputation_points', models.IntegerField(default=0)),
            ],
        ),
    ]
