# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solutionId', models.CharField(max_length=15)),
                ('metrics', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitorSolutionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionId', models.CharField(max_length=15)),
                ('metrics', models.TextField()),
            ],
        ),
    ]
