# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problemId', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=500)),
                ('profileImage', models.CharField(max_length=200)),
                ('date', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentId', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=500)),
                ('profileImage', models.CharField(max_length=200)),
                ('date', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
