# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractNumber', models.AutoField(primary_key=True, serialize=False)),
                ('agreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('agreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolverContract',
            fields=[
                ('contractNumber', models.AutoField(primary_key=True, serialize=False)),
                ('agreed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SolverDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('agreed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartcontract.SolverContract')),
            ],
        ),
    ]
