# Generated by Django 3.0.6 on 2020-10-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateapi', '0002_auto_20201003_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personal',
            name='img',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
