# Generated by Django 3.0.6 on 2020-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateapi', '0003_auto_20201003_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personal',
            name='img',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
