# Generated by Django 3.0.6 on 2020-10-02 20:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateapi', '0004_auto_20201003_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personal',
            name='img',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='upload'),
        ),
    ]
