# Generated by Django 3.0.6 on 2020-10-02 20:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('updateapi', '0005_auto_20201003_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personal',
            name='displaydomains',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=105, null=True, size=5)),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='domains',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=105, null=True, size=5)),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='gender',
            field=models.CharField(blank=True, choices=[('Large', 'Large'), ('FeLarge', 'FeLarge'), ('Other', 'Other')], default='M', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='img',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_personal',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
