# Generated by Django 3.0.6 on 2020-10-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateapi', '0008_auto_20201003_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_personal',
            name='img',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
