# Generated by Django 3.0.6 on 2020-10-02 19:11

import cloudinary_storage.storage
import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField(default=0)),
                ('option', models.CharField(default='None', max_length=50)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CreateSurvey',
            fields=[
                ('surveyID', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 10, 3, 0, 41, 21, 685493))),
                ('alive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solutionId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=10000)),
                ('abstract', models.CharField(max_length=10000)),
                ('docs', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents')),
                ('image', models.ImageField(null=True, upload_to='solution_images')),
                ('video', models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='videos')),
                ('soln_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('level', models.CharField(default='unsolved', max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('members', models.CharField(blank=True, max_length=500, verbose_name=django_mysql.models.ListTextField(models.CharField(max_length=100), size=5))),
                ('collaboration', models.BooleanField(default=False)),
                ('voted_list', django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, size=None)),
                ('waiting_list', django_mysql.models.ListTextField(models.CharField(max_length=100), blank=True, size=None)),
                ('briliant', models.IntegerField(default=0)),
                ('practical', models.IntegerField(default=0)),
                ('eco', models.IntegerField(default=0)),
                ('ww', models.IntegerField(default=0)),
                ('inaccurate', models.IntegerField(default=0)),
                ('inadequate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQ',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionNo', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=50)),
                ('questionType', models.CharField(default='SingleLine Text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TakeSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', django_mysql.models.ListTextField(models.CharField(max_length=250), blank=True, size=None)),
                ('ans', django_mysql.models.ListTextField(models.CharField(max_length=250), blank=True, size=None)),
            ],
        ),
    ]
