# Generated by Django 3.0.6 on 2020-10-02 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20201003_0041'),
        ('updateapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takesurvey',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='takesurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.CreateSurvey'),
        ),
        migrations.AddField(
            model_name='surveyq',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.CreateSurvey'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problemId',
            field=models.ForeignKey(db_column='problemId', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='solution',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updateapi.ExpertPanel'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='expertHelp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updateapi.ExpertHelp'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='problemId',
            field=models.ForeignKey(db_column='problemId', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='solutionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution'),
        ),
        migrations.AddField(
            model_name='createsurvey',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createsurvey',
            name='pblmID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AddField(
            model_name='choice',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.CreateSurvey'),
        ),
    ]
