# Generated by Django 3.0.6 on 2020-10-02 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20201003_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsurvey',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 2, 4, 45, 12911)),
        ),
    ]
