from django.urls import path
from . import views

urlpatterns = [
    path('', views.apiOverview, name="api-overview"),
    path('createcommunity/',
         views.createCommunity, name="Create Community"),
    path('getcommunities/',
         views.getCommunityList, name="problemcommentget"),
    path('newcommunity/',
         views.newCommunity, name="newcommunity"),
    path('addChat/',
         views.addChat, name="addChat"),
    path('getCommunityChat/<str:pk>/',
         views.getCommunityChat, name="getCommunityChat"),
    path('joinCommunity/',
         views.joinCommunity, name="joinCommunity"),
    path('createSubscribedCommunityList/',
         views.createSubscribedCommunityList, name="createSubscribedCommunityList"),
    path('getyourcommunity/<str:pk>/',
         views.getYourCommunity, name="getYourCommunity"),
    path('getsubscribedcommunity/<str:pk>/',
         views.getSubscribedCommunity, name="getSubscribedCommunity"),
    path('getunapprovemembers/<str:pk>/',
         views.getUnApproveMembers, name="getUnApproveMembers"),
    path('allowmember/',
         views.allowMember, name="allowMember"),
    path('blockmember/',
         views.blockMember, name="blockMember"),
    path('checkuser/',
         views.checkUser, name="checkUser"),
    path('dislike/<str:username>/<str:chatId>/',
         views.disLike, name="disLike"),
    path('addlike/<str:username>/<str:chatId>/',
         views.addLike, name="addlike"),
    path('problemcomment/add/',
         views.addCommentToProblem, name="problemcommentadd"),
    path('problemcomment/<str:pk>/',
         views.getProblemComments, name="problemcommentget"),
    path('replycomment/add/',
         views.addReplyComment, name="replycommentadd"),
    path('replycomment/<str:pk>/',
         views.getReplyComments, name="replycommentget"),
    path('test/',
         views.test, name="test"),

]
