# Generated by Django 3.0.6 on 2020-10-02 19:11

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderReq',
            fields=[
                ('reqID', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=500)),
                ('budget', models.IntegerField(default=0)),
                ('attach', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents')),
                ('accept', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('verify', models.BooleanField(default=False)),
                ('vendor', models.CharField(default=None, max_length=50)),
                ('techno', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('time', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('quantity', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('Stype', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('core', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('os', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('speed', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('storage', django_mysql.models.ListTextField(models.CharField(max_length=50), blank=True, size=None)),
                ('depend', django_mysql.models.ListTextField(models.CharField(max_length=250), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.DataProviderReq')),
            ],
        ),
        migrations.CreateModel(
            name='DPInvolved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents')),
                ('reqID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.DataProviderReq')),
            ],
        ),
    ]
